### ISSUE TITLE
Test: isMaximized trouble on old macOS

### ISSUE THREAD

**Issue by macdeport** [Kalmat/PyWinCtl#1]
``
$ pytest -vv test_pywinctl.py
=============================================================== test session starts ================================================================
platform darwin -- Python 3.9.10, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /opt/local/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
cachedir: .pytest_cache
rootdir: /Users/alain/Documents/Logiciels/Developpement/tkinter/pyautogui
collected 0 items                                                                                                                                  

============================================================== no tests ran in 0.00s ===============================================================
ERROR: file or directory not found: test_pywinctl.py

$s3:pyautogui|alain$pytest -vv test_pywinctl.py
=============================================================== test session starts ================================================================
platform darwin -- Python 3.9.10, pytest-6.2.5, py-1.10.0, pluggy-1.0.0 -- /opt/local/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
cachedir: .pytest_cache
rootdir: /Users/alain/Documents/Logiciels/Developpement/tkinter/pyautogui
collected 1 item                                                                                                                                   

test_pywinctl.py::test_basic FAILED                                                                                                          [100%]

===================================================================== FAILURES =====================================================================
____________________________________________________________________ test_basic ____________________________________________________________________

    def test_basic():
    
        if sys.platform == "win32":
            subprocess.Popen('notepad')
            time.sleep(0.5)
    
            testWindows = [pywinctl.getActiveWindow()]
            # testWindows = pywinctl.getWindowsWithTitle('Untitled - Notepad')   # Not working in other languages
            assert len(testWindows) == 1
    
            npw = testWindows[0]
    
            basic_win32(npw)
    
        elif sys.platform == "linux":
            subprocess.Popen('gedit')
            time.sleep(5)
    
            testWindows = [pywinctl.getActiveWindow()]
            assert len(testWindows) == 1
    
            npw = testWindows[0]
    
            basic_linux(npw)
    
        elif sys.platform == "darwin":
            subprocess.Popen(['touch', 'test.txt'])
            time.sleep(2)
            subprocess.Popen(['open', '-a', 'TextEdit', 'test.txt'])
            time.sleep(5)
    
            testWindows = pywinctl.getWindowsWithTitle('test.txt')
            assert len(testWindows) == 1
    
            npw = testWindows[0]
    
>           basic_macOS(npw)

test_pywinctl.py:48: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

npw = MacOSWindow(hWnd=<NSRunningApplication: 0x7fd0b8dc3250 (com.apple.TextEdit - 37855)>)

    def basic_macOS(npw):
    
        assert npw is not None
    
        wait = True
        timelap = 0.00
    
        # Test maximize/minimize/restore.
        if npw.isMaximized:  # Make sure it starts un-maximized
            npw.restore(wait=wait)
    
        assert not npw.isMaximized
    
        npw.maximize(wait=wait)
        time.sleep(timelap)
>       assert npw.isMaximized
E       assert False
E        +  where False = MacOSWindow(hWnd=<NSRunningApplication: 0x7fd0b8dc3250 (com.apple.TextEdit - 37855)>).isMaximized

test_pywinctl.py:393: AssertionError
============================================================= short test summary info ==============================================================
FAILED test_pywinctl.py::test_basic - assert False
================================================================ 1 failed in 13.33s ================================================================
``
Cheers

**Comment by Kalmat** [comment]
Hey! I hope you are doing well!!! Thank you for pointing out this issue.

Problem found (my fault, I didn't try this on Yosemite). I changed the way of invoking Apple Scripts following this:
https://stackoverflow.com/questions/69774133/how-to-use-global-variables-inside-of-an-applescript-function-for-a-python-code

For example, like this:

```

          cmd = """on run {arg1, arg2}
                      set appName to arg1 as string
                      set winName to arg2 as string
                      tell application "System Events" to tell application appName
                          tell window winName to set zoomed to true
                      end tell
                  end run"""
            proc = subprocess.Popen(['osascript', '-', self._appName, self.title],
                                    stdin=subprocess.PIPE, stdout=subprocess.PIPE, encoding='utf8')
            ret, err = proc.communicate(cmd)

```

This is not working the same way in Catalina and above than in "older" versions. I have to figure out how to...

**Comment by Kalmat** [comment]
Rolled back to previous arguments injection style. It seems to be working fine on Yosemite now.

I will keep on searching for a smarter solution.

Thanks again!

**Comment by macdeport** [comment]
All tests passed with Yosemite :-)
