### ISSUE TITLE
Best way from (app,title,condition) to window object?

### ISSUE THREAD

**Issue by macdeport** [Kalmat/PyWinCtl#10]
What is the best way to get the window object from `(app,title,condition)` e.g. the window object which has title found by `getWindowsWithTitle()`?

**Comment by Kalmat** [comment]
Hi!

`getWindowsWithTitle()` actually returns a list of window objects, so I think it's the best way to get it. Refining the search enough, `getWindowsWithTitle()[0]` should be the one you're looking for! (if it exists, of course, because the list can be empty).

**Comment by macdeport** [comment]
Of course, thank you for your patient response to my stupid question. Sorry about that.

**Comment by Kalmat** [comment]
No worries! It's really hard to have all functionalities in mind even for myself!
