### ISSUE TITLE
Issue with installing PyWinCtl failing when importing Numpy

### ISSUE THREAD

**Issue by eviltweedle** [Kalmat/PyWinCtl#13]
Hi, 

I am using python 3.6.8 for a specific purpose in OBS Studio. I have Numpy 19.5-cp36-cp36m-win_amd64.whl isntalled. 

I have the wheel file PyWinCtl-0.0.35-py3-none-any.whl for PyWinCtl and am trying to install it. It repeatedly fails on the Numpy step. 

The full error is:

pip install pywinctl-0.0.35-py3-none-any.whl
Processing c:\users\thebo\pywinctl-0.0.35-py3-none-any.whl
Collecting pywin32>=302; sys_platform == "win32" (from pywinctl==0.0.35)
  Using cached https://files.pythonhosted.org/packages/70/94/44ec60e63d77fb3bb9ff91e6906baf3e750445dc8b6b8374d1c6d79c9412/pywin32-304-cp36-cp36m-win_amd64.whl
Collecting numpy~=1.21 (from pywinctl==0.0.35)
  Could not find a version that satisfies the requirement numpy~=1.21 (from pywinctl==0.0.35) (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5)
No matching distribution found for numpy~=1.21 (from pywinctl==0.0.35)
You are using pip version 18.1, however version 21.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

I'm relatively new to Python and I don't know how to get past this point. I hoped installing Numpy on it's own would get past this but it's not so any help would be appreciated. I have no other version of Python installed, only 3.6.8. 

Kind Regards,

EV

**Comment by Kalmat** [comment]
Hi!

The problem is just the numpy version. 1.19.5 is an old version that I have not tested, this is why I set 1.21 and above as required versions for pywinctl module. Since you actually need Python 3.6, I will test on that version using numpy-1.19. If it works (I think it will), I will modify the pywinctl module installation requirements so it doesn't complain in your case.

**Comment by Kalmat** [comment]
Hi again!

Tested OK with numpy-1.19.5 as expected. I have uploaded a new wheel which allows to install pywinctl with older numpy versions. It should work on your system now. Just download the new wheel from [dist folder](https://github.com/Kalmat/PyWinCtl/tree/master/dist) and install it using:

`pip install PyWinCtl-0.0.35-py3-none-any.whl`

or

`python3 -m pip install PyWinCtl-0.0.35-py3-none-any.whl`

Please, let me know if you get to install it and if you find any issues when using it.

Best Regards,

**Comment by eviltweedle** [comment]
Thanks so much Alef, I will try this out later today and let you know the results

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by eviltweedle** [comment]
Thanks Alef - that's worked and has been successfully installed. I ran CMD as admin and used the command 

`python -m pip install pywinctl-0.0.35-py3-none-any.whl`
