### ISSUE TITLE
Window is not behind Icons

### ISSUE THREAD

**Issue by Fidode07** [Kalmat/PyWinCtl#16]
Hello.

Here is my Code:

```
def move_behind(title: str):
    all_windows: list = pwc.getAllWindows()

    for window in all_windows:
        my: pwc.LinuxWindow = window
        if my.title == title:
            my.sendBehind()


move_behind("ItsABackground")
```
The Issue is with every Window. I use Ubuntu with installed KDE (kde-standard) in Plasma.

**Comment by Fidode07** [comment]
Thanks for the quick reply. Sad that it doesn't work, anyway I can bring out my WallpaperEngine for Cinnamon at least. And the question on Stackoverflow, only through this I found the project here. I will look at Xlib again, but I don't think I can find a way. 

Thanks for your help and time!

**Comment by Kalmat** [comment]
Yes, it's a real pitty I couldn't find a solution. I tried absolutely everything that I could imagine: reparent the window to all possible parents, configure it as desktop-type window, use Xlib library directly, besides thru python-xlib, to set a number of window attributes and properties combinations... all in vain. I have to admit I am totally lost here... I will try to search and ask again just to try my luck!

Thank you for your interest and support!

**Comment by Fidode07** [comment]
I downloaded Linux Mint Cinnamon, but the window was not behind the icons there either. The code is the same.
Any idea?

**Comment by Kalmat** [comment]
Hi again!  Sorry for the delay in the reply. I've been out on travel.

It's not working for me either. Perhaps a recent update has "broken" something (in fact, I was using an ugly "hack" to make it work on Mint/Cinnamon). I will look into it and will let you know any progress.

**Comment by Kalmat** [comment]
Hi!

I found a different hack to make it work on Mint/Cinnamon (unfortunately, it does not work in Ubuntu). Please try this wheel and tell me if it works.

Unzip the file and install it by running this on a terminal:

```
cd /path/to/folder/where/the/wheel/file/was/downloaded
python3 -m pip uninstall pywinctl
python3 -m pip install PyWinCtl-0.0.38-py3-none-any.whl
```
[PyWinCtl-0.0.38-py3-none-any.whl.zip](https://github.com/Kalmat/PyWinCtl/files/9045999/PyWinCtl-0.0.38-py3-none-any.whl.zip)

**Comment by Kalmat** [comment]
Hi again! Found a solution which seems to work OK on Ubuntu/GNOME (only version 22.04 and above) and Mint/Cinnamon.

If you are still interested, install wheel file (PyWinCtl-0.0.40-py3-none-any.whl) located in dist folder and let me know any comment or issue.

**Comment by Kalmat** [comment]
Hi again! New version (0.0.42) includes a solution which seems to work OK on Ubuntu/GNOME (only version 22.04 and above) and Mint/Cinnamon.

If you are still interested, install wheel file (PyWinCtl-0.0.42-py3-none-any.whl) located in dist folder and let me know any comment or issue.
