### ISSUE TITLE
how to use "alwaysOnTop" on MacOS?

### ISSUE THREAD

**Issue by kingtosh** [Kalmat/PyWinCtl#17]
I tried "alwaysOnTop" on MacOS, but got error.
So please tell me how to use "alwaysOnTop".

**Comment by Kalmat** [comment]
Hi!

can you please copy-paste the code you are using? Are you trying to use this method on your own application or on a window from another app?

**Comment by kingtosh** [comment]
Hi, thank you for your reply.
I used code like the below.
$ python
>>> import pywinctl as pwc
>>> pwc.getWindowsWithTitle('window name like desktop etc.')
>>> win = pwc.getWindowsWithTitle('Desktop')[0]
>>> win.alwaysOnTop

then I got some errors.
referring page - https://dev.classmethod.jp/articles/macbook-manipulating-windows-in-python-pywinctl/
(sorry that's Japanese site)

**Comment by Kalmat** [comment]
Hi again!

I see now. You are trying to keep another app's window always on top (not YOUR app, I mean).

In such a case, try this:

```
import pywinctl as pwc

print(pwc.getAllTitles())
windows = pwc.getWindowsWithTitle("Finder")
if windows:
    for w in windows:
        print(w.title)
    win = windows[0]
    win.alwaysOnTop()  # Note the parenthesis!
else:
    print("No window found with that title")
```

Note that very likely there won't be any app called "Desktop", so I replaced it by "Finder" instead. Also note that not all apps will allow to be manipulated using AppleScript (which is required to manipulate other app's windows). Finally, you will need to grant scripting permissions for the Terminal (if you are running your script on the terminal, of course). This can be done accessing Settings-->Security&Privacy--> Accessibility

Please send me the output of your Terminal when you run this.

Which macOS version you have?

**Comment by Kalmat** [comment]
Hi! Sorry for reaching you again. Do you still need help on this? If so, let me know how can I help you. If it is not the case, do you agree to close the issue?
