### ISSUE TITLE
Allow setting custom screen dimensions to use

### ISSUE THREAD

**Issue by HQRaja** [Kalmat/PyWinCtl#23]
Thank you for this script - it works flawlessly for most use cases. However, I have an edge case where I'm using a 5120x1440p monitor and I only want to share the first half of its screen i.e. 2560x1440p. After adding the source, I have cropped 2560p from its right side, and then resized it to 1920x1080p, which is my canvas size. However, upon using your script, each time it zooms out, it resets the crop to 5120x1440p using a filter, and I don't see an option in the script's settings to specify a custom value for those dimensions (which in my case would be 2560x1440).

Can you please add the option to use custom values for these in the script's settings? (You could still default to getting these values from the monitor's default resolution, but provide a check box for those with a use case like me to override those default values.)

**Comment by Kalmat** [comment]
Hi! Sorry but I'm affraid I don't fully understand your issue. Perhaps you are referring to the [obs-zoom-and-follow](https://github.com/tryptech/obs-zoom-and-follow) script? If so, please open this issue in that repository. I know the author (tryptech) usually attends all issues.

**Comment by HQRaja** [comment]
@Kalmat oh I'm so sorry, I thought I had posted this in the obs-zoom-and-follow repo, but it seems I posted here by mistake since I had this repo open in a tab next to that one. My bad.

**Comment by Kalmat** [comment]
HAHAHAHA! No worries! We all are humans in the end. I hope you find a solution.

**Comment by HQRaja** [comment]
Thank you! Since this issue is irrelevant, I want to delete it, bit can't seem to find the option, so please feel free to delete it if you have the option.
