### ISSUE TITLE
This is not getting windows that are minimized, maybe because this only gets "visible" windows?

### ISSUE THREAD

**Issue by brockbrownwork** [Kalmat/PyWinCtl#31]
Hi there. I was on the PyGetWindow issues page, and you directed me here. I have replaced PyGetWindow with PyWinCtl, and I am still experiencing the same issue where if a window is minimized, it does not detect the window with getWindowsWithTitle.
Thanks

**Comment by brockbrownwork** [comment]
Also this does not detect windows at all, even if they're not minimized, compared to when I am using PyGetWindow. I am running Windows 10.

**Comment by Kalmat** [comment]
Hi! Can you please paste your code?

Also, give a try to this:

```
import pywinctl as pwc

for w in pwc.getAllWindows()
    print(w.title)
```

Is your target window listed?
