### ISSUE TITLE
Window.activate() fails to truly bring windows to front on Linux (X11/Unity)

### ISSUE THREAD

**Issue by MestreLion** [Kalmat/PyWinCtl#36]
Consider this prototype:

```python
import pywinctl

def activate(title: str):
    windows = pywinctl.getWindowsWithTitle(title)
    if not windows:
        return False
    return windows[0].activate()
```

The problem is: at least in Ubuntu/Unity DE, but most likely other DEs, this only flashes/vibrates the window icon in the taskbar, setting its `_NET_WM_STATE_DEMANDS_ATTENTION`. Digging the underlying `ewmh` library I believe I figured the problem: `EWHM.setActiveWindow()`  is sending the `X` client message with a [Source Indication](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#sourceindication) of **1**, and this allows the WM to (almost) ignore it. If using a source indicator of **2** it works perfectly!

```python
# Monkey-patching ewmh
import ewmh
def setActiveWindow(self: ewmh.EWMH, win: ewmh.ewmh.display.drawable.Window):
    self._setProperty('_NET_ACTIVE_WINDOW', [2, ewmh.ewmh.X.CurrentTime, win.id], win)
ewmh.EWMH.setActiveWindow = setActiveWindow

import pywinctl

def activate(title: str):
    windows = pywinctl.getWindowsWithTitle(title)
    if not windows:
        return False
    return windows[0].activate()
```

**Comment by MestreLion** [comment]
If wanted I can provide a PR with a more friendly approach:
- Monkey-patch only `pywinctl.EWMH` _instance_, so it does not interfere with other clients
- Add a `source:int=1` argument to `EWMH.setActiveWindow`, so it preserves original behavior while still allowing customization
- Add a `force:bool=False` argument to pywinctl.LinuxWindow.activate()` so the user can choose the source indicator.

**Comment by Kalmat** [comment]
Thank you! I do really appreciate your interest and work!

First off, which version of Ubuntu and Unity you have so I am able to replicate your very same setup? I already tested the module with Ubuntu/Unity but likely not the same config and for sure I didn't realize this issue you are pointing out.

Second, of course your contribution is more than welcome! In fact, if you are skilled in Xlib, or you think you can help in any way, I would encourage you to take a look to the whole module to help improve it (I am not a real Xlib expert so for sure things can be done better, and I also had a hard time with some features, e.g. with sendBehind() and some others)

Third, does this happens only when the window is minimized or does it also happens when the window is on screen but it's not the focused window? This is important so we can decide how we want activate() to work. Let me explain myself and analyze together which alternatives me may have to solve this issue:

I see you did an awesome investigation, thanks a lot! Reading the documentation you linked, it states: "1 for normal applications, and 2 for pagers and other Clients that represent direct user actions", so I am not sure if using the value of "2" it's going to work as expected in all distributions and WMs combinations. Since the desired behavior is to set the window as focused, perhaps setting `'_NET_WM_STATE_FOCUSED'` together with `'_NET_ACTIVE_WINDOW`' can do the trick in this case. To bring back a window from minimized state the proper function, I guess, should be `restore()`, then you can decide to activate (focus) it, or not. So the solution could be: `restore()`, then `activate()`; or, as you propose, activate should intrinsically mean: `restore()`, if required, then `activate()` (set focus, which is something that currently the method is not doing since it was enough with activate() in GNOME and other WMs).

If this does not work in all cases, another alternative could be to ask for the WM inside `activate()` method so, as you propose, we can use "2" as source indication if the WM is Unity (`if "unity" in os.environ.get('XDG_CURRENT_DESKTOP', '').lower():`). The advantage in this case is that (I think) doesn't affect to other users using older versions.

Please let me know your thoughts on all this! In the meantime, and with the aim of having as much info as possible, could you please be so kind to test this on your system and check it it restores the window from minimized state and sets it as the focused window?

```
import ewmh
import Xlib.display
import Xlib.X
import Xlib.Xatom

import time
import pywinctl as pwc


DISP = Xlib.display.Display()
SCREEN = DISP.screen()
ROOT = SCREEN.root
EWMH = ewmh.EWMH(_display=DISP, root=ROOT)

w = pwc.getActiveWindow()
w.minimize()
time.sleep(2)

# OPTION 1
EWMH.setActiveWindow(w.getHandle())
EWMH.display.flush()
EWMH.setWmState(w.getHandle(), 1, '_NET_WM_STATE_ABOVE', '_NET_WM_STATE_FOCUSED')
EWMH.display.flush()
time.sleep(2)

w.minimize()
time.sleep(2)

# OPTION 2 (in case ewmh doesn't properly work for all properties)
pos = w.topleft
win = DISP.create_resource_object('window', w.getHandle().id)
win.unmap()
win.change_property(DISP.intern_atom('_NET_WM_WINDOW_TYPE', False), Xlib.Xatom.ATOM,
                  32, [DISP.intern_atom('_NET_WM_WINDOW_TYPE_NORMAL', False), ],
                  Xlib.X.PropModeReplace)
DISP.flush()
win.configure(stack_mode=Xlib.X.Above)
DISP.flush()
win.change_property(DISP.intern_atom('_NET_WM_STATE', False), Xlib.Xatom.ATOM,
                  32, [DISP.intern_atom('_NET_WM_STATE_FOCUSED', False), ],
                  Xlib.X.PropModeAppend)
DISP.flush()
win.map()  # I have doubts on wether this should go here or BEFORE setting the focus...
EWMH.setActiveWindow(w.getHandle())
w.moveTo(pos.x, pos.y)
```

Sorry if it's not properly working. For an unknown reason, my Ubuntu installation (virtual machine) is now returning None when invoking EWMH.getActiveWindow() or DISP.get_input_focus().focus (!?!?!?!?!?!)

Thanks in advance!

**Comment by MestreLion** [comment]
Wow, what a detailed reply, thanks! I'll breakdown my answer in small bits as there are a lot of (overlapping) things in this subject.

> First off, which version of Ubuntu and Unity you have

Using Ubuntu 18.04 LTS (almost EOL, I know...), Unity 7.5.0+18.04.20190304-0ubuntu1 and Compiz (the actual WM backend) 1:0.9.13.1+18.04.20180302-0ubuntu1, all from Ubuntu's repository

> I already tested the module with Ubuntu/Unity but likely not the same config and for sure I didn't realize this issue you are pointing out.

Freedesktop's latest EWMH Spec is more than a decade over, so I'd be surprised if anything has changed in Compiz's behavior / interpretation.

Actually, the calls from PyWinCtl and EWMH are correct, they are _requesting_ the window to be activated, but Compiz/Unity is interpreting this request as "just vibrate the app icon in the taskbar and make the small triangle marker blue" without bringing the window to front or focusing it.

> Second, of course your contribution is more than welcome! In fact, if you are skilled in Xlib, or you think you can help in any way, I would encourage you to take a look to the whole module to help improve it (I am not a real Xlib expert so for sure things can be done better, and I also had a hard time with some features, e.g. with sendBehind() and some others)

Thanks! But this is my first time dealing with XLib, so much less of an expert than you! lol. That said, I do have a few suggestions for the API, will do so in other issues so we don't get too much off-topic in this one. Spoiler alert: `ewmh` (the module, not the spec) is showing its age, and seems unmaintained. As you're already importing `Xlib`, maybe it's time to consider progressively replacing `ewmh`  with direct Xlib calls and eventually dropping it completely.

**Comment by MestreLion** [comment]
> please be so kind to test this on your system and check it it restores the window from minimized state and sets it as the focused window?

```python
...
w = pwc.getActiveWindow()
w.minimize()
time.sleep(2)
```
Minimizes correctly, and focus switches to another window, as expected.

```python
# OPTION 1
EWMH.setActiveWindow(w.getHandle())
EWMH.display.flush()
```
This only "animates" the icon the icon in the taskbar, like this: 
![Screenshot from 2023-01-16 08-47-42](https://user-images.githubusercontent.com/992317/212672804-86f0760d-660c-42af-a0d2-5d5cb7ffcd91.png)

It does not "unminimize"/restore nor change the focused window.

```python
EWMH.setWmState(w.getHandle(), 1, '_NET_WM_STATE_ABOVE', '_NET_WM_STATE_FOCUSED')
EWMH.display.flush()
time.sleep(2)
```
Initially it seems to do nothing: still no "unminimize"/restore, and no focus swiching. _But_, after the script ended and I manually restored it, it was "sticky" to be always on top even when not focused (the same behavior as `w.alwaysOnTop()`)

```python
w.minimize()
time.sleep(2)
```
as the window was already minimized, it did nothing

**Comment by MestreLion** [comment]
I've skipped all `# OPTION 1` for this run, so this begins with the former active window minimized:

```python
# OPTION 2 (in case ewmh doesn't properly work for all properties)
pos = w.topleft
win = DISP.create_resource_object('window', w.getHandle().id)
win.unmap()
DISP.flush()  # I added this to help testing
```
App icon disappears from taskbar, as if it was closed.

```python
win.change_property(DISP.intern_atom('_NET_WM_WINDOW_TYPE', False), Xlib.Xatom.ATOM,
                  32, [DISP.intern_atom('_NET_WM_WINDOW_TYPE_NORMAL', False), ],
                  Xlib.X.PropModeReplace)
DISP.flush()
win.configure(stack_mode=Xlib.X.Above)
DISP.flush()
win.change_property(DISP.intern_atom('_NET_WM_STATE', False), Xlib.Xatom.ATOM,
                  32, [DISP.intern_atom('_NET_WM_STATE_FOCUSED', False), ],
                  Xlib.X.PropModeAppend)
DISP.flush()
```
Nothing seems to happen (window is still invisible)

```python
win.map()  # I have doubts on wether this should go here or BEFORE setting the focus...
DISP.flush()  # I (MestreLion) added this
```
App icon shows in the taskbar _with_ the "focused" animation. But it's still minimized, no window

```python
EWMH.setActiveWindow(w.getHandle())
w.moveTo(pos.x, pos.y)
```
Nothing happens, not even the animation, perhaps because the triangle marker was already blue (I don't think you can animate it twice before user manually intervenes)

> For an unknown reason, my Ubuntu installation (virtual machine) is now returning None when invoking EWMH.getActiveWindow() or DISP.get_input_focus().focus (!?!?!?!?!?!)

`EWMH.getActiveWindow()` worked fine here. I'll try to test `DISP.get_input_focus().focus`.

**Comment by MestreLion** [comment]
> Third, does this happens only when the window is minimized or does it also happens when the window is on screen but it's not the focused window? This is important so we can decide how we want activate() to work.

It happens regardless if window is minimized or simply not focused: Compiz only animates the taskbar icon on `EWMH.setActiveWindow()`, it does not bring window to front or focus it.

I believe this a design decision of Compiz when using `1` as the request _source_: as the EWMH Spec says, this means "triggered by another application", so the WM can, quoting the spec:

> Depending on the information provided with the message, the Window Manager may decide to refuse the request (either completely ignore it, or e.g. use _NET_WM_STATE_DEMANDS_ATTENTION). 

Which is **exactly** what Unity/Compiz is doing. When using `2` (or `0`, as `wmctrl` does) it **does** it all: restore if minimized, bring to front and focus.

**Comment by MestreLion** [comment]
> Since the desired behavior is to set the window as focused, perhaps setting `'_NET_WM_STATE_FOCUSED'` together with `'_NET_ACTIVE_WINDOW`' can do the trick in this case.

I'm not familiar enough with XLib/Ewmh spec to know the difference between these 2. Intuitively I've always assumed "active" as either a synonym or at least a superset of "focused".

> To bring back a window from minimized state the proper function, I guess, should be `restore()`, then you can decide to activate (focus) it, or not. So the solution could be: `restore()`, then `activate()`; or, as you propose, activate should intrinsically mean: `restore()`, if required, then `activate()` (set focus, which is something that currently the method is not doing since it was enough with activate() in GNOME and other WMs).
> ...
> Please let me know your thoughts on all this!

Ok, now we're digging into the heart of the issue: what are `w.activate()` and `w.restore()` supposed to do, and how? I didn't read Ewmh Spec yet, so these are my thoughts as a mere user:

- `w.restore()` should only deal with windows "size": to go from minimized or maximized to "windowed". If possible it should not bring to front and definitely not give it focus.
- `w.activate()` should mean "unminimize if needed, bring to front _and_ give it focus" combo, so yes, it intrinsically means `w.restore()` _if minimized_, as you can't "bring to front" or "give focus" to a minimized window.

The problem is, by the spec no WM is _required_ to do so if using 1 as source. They can simply set a "demand attention" status or even completely ignore the request. As a side note: `0`, as used by pre-spec software such as `wmctrl`, also made Compiz comply.

> If this does not work in all cases, another alternative could be to ask for the WM inside `activate()` method so, as you propose, we can use "2" as source indication if the WM is Unity (`if "unity" in os.environ.get('XDG_CURRENT_DESKTOP', '').lower():`). The advantage in this case is that (I think) doesn't affect to other users using older versions.

Special-casing Unity seems a little "hackish", and besides the burden of choosing should not be on you.

> I am not sure if using the value of "2" it's going to work as expected in all distributions and WMs combinations. 

I don't see why it shouldn't, at least for compliant WMs.

And I'm not suggest you _change_ to 2, but merely to _offer_ such option: let the _user_ choose this depending on his use-case: 1 to let the WM decide, 2 to "force" it, and hence my suggestion of a new `force:bool=False` flag. You _could_ make the default to be `True` if you don't mind breaking current behavior (and potentially meeting more user expectations), but the option alone would already be enough for me.

**Comment by MestreLion** [comment]
Also, I just noticed this regarding [`_NET_ACTIVE_WINDOW`](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm45154644305408):

> If a Client wants to activate another window, it MUST send a _NET_ACTIVE_WINDOW client message to the root window:
> ```
>  window  = window to activate
>  message_type = _NET_ACTIVE_WINDOW
>  format = 32
>  data.l[0] = source indication 
>  data.l[1] = timestamp
>  data.l[2] = requestor's currently active window, 0 if none
>  other data.l[] elements = 0
> ```
> Source indication should be 1 when the request comes from an application, and 2 when it comes from a pager. Clients using older version of this spec use 0 as source indication, see [the section called “Source indication in requests”](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#sourceindication) for details. The timestamp is Client's last user activity timestamp (see _NET_WM_USER_TIME) at the time of the request, and the currently active window is the Client's active toplevel window, if any (the Window Manager may be e.g. more likely to obey the request if it will mean transferring focus from one active window to another).
>
> Depending on the information provided with the message, the Window Manager may decide to refuse the request (either completely ignore it, or e.g. use _NET_WM_STATE_DEMANDS_ATTENTION).

So far, to "force" Unity/Compiz not to ignore the request, I've only tried to fiddle with `data.l[0] = source indication`. 2 worked so I was happy.

But that about `data.l[2] = requestor's currently active window, 0 if none` ? Is `ewmh` using `0` or the actual id of the currently active window? If `0`, this could be the reason Compiz refused the request: _the Window Manager may be e.g. more likely to obey the request if it will mean transferring focus from one active window to another_

So maybe the source indicator is not the only way of solving this?

Either way, I'd still like to have an option to set source to 2. After all, for _my_ use-case (and I believe for many users) PyWinCtl **is** a proxy for "direct user action". I'm using it with PyAutoGui to emulate user actions, so I need to be sure windows are properly set to front, focused, etc.

**Comment by Kalmat** [comment]
WoW!!! Thank you for all your time and this awesome reply! This kind of discussions really help me a lot!!!

> Freedesktop's latest EWMH Spec is more than a decade over, so I'd be surprised if anything has changed in Compiz's behavior / interpretation.
> 
> Actually, the calls from PyWinCtl and EWMH are correct, they are _requesting_ the window to be activated, but Compiz/Unity is interpreting this request as "just vibrate the app icon in the taskbar and make the small triangle marker blue" without bringing the window to front or focusing it

Sorry for not having been clear enough. I didn't mean it didn't happen in my tests, I was saying that I didn't realize!! so thank you for pointing it out!!!

> Either way, I'd still like to have an option to set source to 2. After all, for _my_ use-case (and I believe for many users) PyWinCtl **is** a proxy for "direct user action". I'm using it with PyAutoGui to emulate user actions, so I need to be sure windows are properly set to front, focused, etc.

Count on it, of course. Do you agree `forceFocus=False` would be the best way to go? I mean using `force` may be understood as "force activation", whilst `forceFocus` may better explain the intended action. Adding `False` as default value, will not change previous behavior for other users. Besides, do you think it's better monkey-patch emwh, or changing the activate() method like this?

    def activate(self, forceFocus: bool = False, wait: bool = False):
        """
        Activate this window and make it the foreground (focused) window

        :param forceFocus: set to ''True'' to force the window to grab focus (some WMs, e.g. Unity, may require it)
        :param wait: set to ''True'' to wait until action is confirmed (in a reasonable time lap)
        :return: ''True'' if window activated
        """
        if "arm" in platform.platform():
            EWMH.setWmState(self._hWnd, ACTION_UNSET, STATE_BELOW, STATE_NULL)
            EWMH.display.flush()
            EWMH.setWmState(self._hWnd, ACTION_SET, STATE_ABOVE, STATE_FOCUSED)
        else:
            # EWMH.setActiveWindow(self._hWnd)
            sourceInd = 2 if forceFocus else 1
            EWMH._setProperty('_NET_ACTIVE_WINDOW', [sourceInd, ewmh.ewmh.X.CurrentTime, self._hWnd.id], self._hWnd)
        EWMH.display.flush()
        retries = 0
        while wait and retries < WAIT_ATTEMPTS and not self.isActive:
            retries += 1
            time.sleep(WAIT_DELAY * retries)
        return self.isActive

I need some time to finish other things I'm working on the module, test and so on but, in the meantime, I can prepare a new wheel so you can start working with it while I upload a new version to PyPi.

> Spoiler alert: `ewmh` (the module, not the spec) is showing its age, and seems unmaintained. As you're already importing `Xlib`, maybe it's time to consider progressively replacing `ewmh` with direct Xlib calls and eventually dropping it completely.

Fully agree. This is something I was considering but had no time (nor enough knowledge, to be honest). Without rushing, but I will definitely work on it.

> Thanks! But this is my first time dealing with XLib, so much less of an expert than you! lol. That said, I do have a few suggestions for the API, will do so in other issues so we don't get too much off-topic in this one.

Though you're not skilled on Xlib, if you think you can help in any way, you are more than welcome.

Again, thanks a lot for your help!

**Comment by MestreLion** [comment]
> Do you agree `forceFocus=False` would be the best way to go? I mean using `force` may be understood as "force activation", whilst `forceFocus` may better explain the intended action.

But the intended action is not to just "give focus": the WM "de-iconify"/""unminimize" it if needed, and also brings the window to the front. So `forceFocus` would be a misnomer, we are _actually_ signaling the WM to obey the whole activation request. Maybe `user_action` or `emulate_user` is more precise than `force`, but I still think `force` is good enough, and the documentation would mention something like:

_`force`: sends the activation request with a source indication of 2 instead of 1, thus telling the WM that this is a direct user action request and (hopefully) force it to comply. The default of `False` uses a source indication of 1, meaning the request comes form a regular application, and some WMs may decide to refuse the request (either completely ignore it, or set `_NET_WM_STATE_DEMANDS_ATTENTION` and its corresponding taskbar animation)._

Or simply:

_`force`: `True` tells the WM this is a direct user action. Some WM such as Unity may ignore the request if this is `False`._

I've spent the last hours reading the Ewmh Spec, as to understand its definition of "_active_" (as a windows status) and "_activation_" (the action). It seems there is no formal ACTIVE _status_, so it's just a synonym for FOCUSED (as receiving user input and possibly have a different, highlighted title bar / decoration. As for "activation" as an _action_,  it seems there is no defined behavior apart from "make it focused", just some suggestions on what it could/should additionally do:

> In the X world, activating a window means to give it the input focus. This may not be possible if the window is unmapped, because it is on a different desktop. Thus, activating a window may involve additional steps like moving it to the current desktop (or changing to the desktop the window is on), deiconifying it or raising it.

So I do believe that `pywinctl.Window.activate()` should really mean "restore if needed, bring to front and give focus". Also, the more I think about it, the more I believe the default `force` should be `True`. 

> Besides, do you think it's better monkey-patch emwh, or changing the activate() method like this?

Both approaches work, and both are bad, either by monkey-patching or directly calling the "**private**" method `EWMH._setProperty()`. Tough call, and I have no firm opinion on that.

Another, more "proper" solution would be to re-implement `_setProperty()` in PyWinCtl, using only direct `XLib` calls, and make your `Window.activate()` use that instead.

**Comment by MestreLion** [comment]
> I need some time to finish other things I'm working on the module, test and so on but, in the meantime, I can prepare a new wheel so you can start working with it while I upload a new version to PyPi.

Nah, don't bother. For my current project I've already monkey-patched `ewmh` myself, so there's no rush on this being integrated in PyWinCtl.

**Comment by MestreLion** [comment]
> Both approaches work, and both are bad, either by monkey-patching or directly calling the "**private**" method `EWMH._setProperty()`. Tough call, and I have no firm opinion on that.
> 
> Another, more "proper" solution would be to re-implement `_setProperty()` in PyWinCtl, using only direct `XLib` calls, and make your `Window.activate()` use that instead.

The "best" solution would be for `ewmh` to either add a source indication argument to `EWMH.activate()` or to rename/create a _public_ `setProperty()` method.

But, given its abandoned state, we both know neither will happen. (and that's why I created this issue here and not there, even though _none_ of this is PyWinCtl's fault.

**Comment by Kalmat** [comment]
Hi again! You definitely convinced me!!! Then, "activate()" will mean "restore if needed, bring to front and give focus" as you propose, and the default behavior will be set to True. I have to check if that is what it is exactly happening in other OSs as well, so I will have to adapt thier behavior, if needed, in order to be coherent.

> Another, more "proper" solution would be to re-implement `_setProperty()` in PyWinCtl, using only direct `XLib` calls, and make your `Window.activate()` use that instead.

That's exactly what I have to work on: replace all ewmh stuff. In the meantime, I was proposing using it for the sake of quickness. This is also why I do prefer the solution of modifying activate() method instead of monkey-patching ewmh module.

You were proposing to open a PR. Please, feel totally free to do it or, if you have other plans, do not worry, I will modify this all and upload a new version as soon as I can.

Thanks!

**Comment by MestreLion** [comment]
> Hi again! You definitely convinced me!!! Then, "activate()" will mean "restore if needed, bring to front and give focus" as you propose, and the default behavior will be set to True.

Great!

> That's exactly what I have to work on: replace all ewmh stuff. In the meantime, I was proposing using it for the sake of quickness. This is also why I do prefer the solution of modifying activate() method instead of monkey-patching ewmh module.

Both approaches are very easy and quick to implement, both "smells" bad, so I'll go with calling the private method since it "looks" less hackish.

> You were proposing to open a PR. Please, feel totally free to do it or, if you have other plans, do not worry, I will modify this all and upload a new version as soon as I can.

OK, I'll work now on the PRs for this and #37. 

Last-minute question: what do you think about `user` instead of `force` as the argument name? It's less intuitive (what is it for?) but is more accurate: we're actually using a source that indicates a direct **user** action, forcing the WM is just _our intention_, not a spec thing.
