### ISSUE TITLE
getAllTitles: list of window titles sorted differently than on screen

### ISSUE THREAD

**Issue by macdeport** [Kalmat/PyWinCtl#4]
Yosemite: it occurs at least with Firefox, Thunderbird and Path Finder.

Windows are stacked object: the stack order is relevant. PyWinCtl's methods must therefore preserve this order for the user to use. For example, the last window on the stack is the one that has the focus.

**Comment by Kalmat** [comment]
Hey! These methods were never intended to take into account the windows/apps stacking. Never the less is a very good point. Some things to take into account:
- Window stacking order can change and be outdated very quickly, so it's something you can not rely on
- getAllWindows() and getAllTitles() output respects windows stacking within a given app, but not the app stacking. App order returned by Apple Script corresponds to when the apps were open (older-to-newer)
- Application Switcher (cmd+tab) doesn't take into account the stacking on screen, but the order of when every app was last used (typically these two sequences match, but not always)
- Last, but most important, I don't think it can be done using Apple Script. I found no query, property or attribute which can be used to obtain the app/process stacking order (for both app stacking on screen and window "last used" stacking)

I will look into it anyway.

**Comment by macdeport** [comment]
> getAllWindows() and getAllTitles() output respects windows stacking within a given app, but not the app stacking. App order returned by Apple Script corresponds to when the apps were open (older-to-newer)

For a given application the question is solved. This is already a good point. 

> Last, but most important, I don't think it can be done using Apple Script.

Maybe useful to check the window index that AppleScript uses: you can access the different windows by "window index n".

**Comment by Kalmat** [comment]
Yes, window index is very useful for this, but it is related to the index within every app. So, every app will have a window 1, and so on. I couldn't find a similar value (index or attribute) for apps. I tried using Quartz.CGWindowListCopyWindowInfo(), but it doesn't return the windows in the screen stacking order either. I found several similar questions on stackoverflow, with no answer... Still searching, though 

Thank you for your help to improve!

**Comment by Kalmat** [comment]
Hi again! Unfortunately, I was not able to find any method to return applications according to their stack order. I don't like to give up at all, so I will shamefully close this issue...

**Comment by macdeport** [comment]
Don't be sorry. It's me following it because I didn't realize in any way the difficulty in practice of such an "obvious" stack order. Note that the WM (Window Manager) necessarily maintains such an ordered list. Thanks for this project and the result already obtained.
