### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by JHOEFEL** [Kalmat/PyWinCtl#77]
How to solve this issue ?
- Python 3.11.5
   command "pip install PyWinCtl" runs only in directory "C:\Users\AJH\AppData\Local\Programs\Python\Python311\Scripts"
- OBS 29.1.3

![2023-09-16 07_48_30-Skriptlog](https://github.com/Kalmat/PyWinCtl/assets/145183172/fc4f57ad-a7b5-4fe0-a974-3af92b3c2a5d)
![2023-09-16 07_55_37-Scripts](https://github.com/Kalmat/PyWinCtl/assets/145183172/1a110ccf-b6b0-4137-a674-21846ea39497)

**Comment by Kalmat** [comment]
Hi! Just run:

`pip install typing-extensions`

**Comment by JHOEFEL** [comment]
Hi – thank´s for support – Everything works fine – Enjoy your weekend :)

 

 

Von: Kalmat ***@***.*** 
Gesendet: Samstag, 16. September 2023 11:42
An: Kalmat/PyWinCtl ***@***.***>
Cc: JHOEFEL ***@***.***>; Author ***@***.***>
Betreff: Re: [Kalmat/PyWinCtl] ModuleNotFoundError: No module named 'typing_extensions' (Issue #77)

 

Hi! Just run:

pip install typing-extensions

**Comment by Kalmat** [comment]
So happy it worked! Same for you!

I'll have to look into it. It shouldn't complain about that.
