### ISSUE TITLE
getAllTitles() says KeyError: 'id'

### ISSUE THREAD

**Issue by lazebird** [Kalmat/PyWinCtl#91]
Python 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pywinctl
>>> pywinctl.getAllTitles()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liulang/.local/lib/python3.11/site-packages/pywinctl/_pywinctl_linux.py", line 129, in getAllTitles
    return [window.title for window in getAllWindows()]
                                       ^^^^^^^^^^^^^^^
  File "/home/liulang/.local/lib/python3.11/site-packages/pywinctl/_pywinctl_linux.py", line 117, in getAllWindows
    windows = [str(win["id"]) for win in windowsList]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liulang/.local/lib/python3.11/site-packages/pywinctl/_pywinctl_linux.py", line 117, in <listcomp>
    windows = [str(win["id"]) for win in windowsList]
                   ~~~^^^^^^
KeyError: 'id'
>>>

**Comment by lazebird** [comment]
Linux deb12-vm 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux
Debian GNU/Linux 12 \n \l

**Comment by lazebird** [comment]
seems it only happens in wayland, x11 is ok

**Comment by m0sk1t** [comment]
@lazebird  Is it fixed or not? on my machine I have the same error...

Linux dev 6.8.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lazebird** [comment]
i changed to x11 desktop, and it works well now
FYI: edit /etc/gdm3/daemon.conf, set WaylandEnable=false

**Comment by lazebird** [comment]
> @lazebird Is it fixed or not? on my machine I have the same error...
> 
> Linux dev 6.8.0-45-generic #45~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Sep 11 15:25:05 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

i changed to x11 desktop, and it works well now
FYI: edit /etc/gdm3/daemon.conf, set WaylandEnable=false
